
const ROLE_ADMIN = 'ADMIN';
const ROLE_USER = 'USER';

const CONFIG_GROUP_BOOKING_EVENT = 'BOOKING_EVENT';
const CONFIG_GROUP_BOOKING_STATUS = 'BOOKING_STATUS';

module.exports = {
    ROLE_ADMIN,
    ROLE_USER,
    CONFIG_GROUP_BOOKING_EVENT,
    CONFIG_GROUP_BOOKING_STATUS
}
