
const ROLE_ADMIN = 'ADMIN';
const ROLE_USER = 'USER';

const CONFIG_GROUP_BOOKING_EVENT = 'BOOKING_EVENT';
const CONFIG_GROUP_BOOKING_STATUS = 'BOOKING_STATUS';

const RESPONSE_STATUS_SUCCESS = 'SUCCESS';
const RESPONSE_STATUS_FAIL = 'FAIL';


module.exports = {
    ROLE_ADMIN,
    ROLE_USER,
    CONFIG_GROUP_BOOKING_EVENT,
    CONFIG_GROUP_BOOKING_STATUS,
    RESPONSE_STATUS_SUCCESS,
    RESPONSE_STATUS_FAIL,
}
